# Generated by Django 6.1.1 on 2026-09-28 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('CLEARED', 'Cleared')], default='LOCKED', max_length=30)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_gates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='home.project')),
            ],
            options={
                'db_table': 'gate',
                'ordering': ['project', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('TASK', 'Task'), ('GATE', 'Gate'), ('HANDOVER', 'Handover'), ('OVERRIDE', 'Override')], max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('CLAIM', 'Claim'), ('RELEASE', 'Release'), ('COMPLETE', 'Complete'), ('EXPIRE', 'Expire'), ('SPLIT', 'Split'), ('GATE_CLEAR', 'Gate clear')], max_length=50)),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='home.project')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('MANAGER', 'Manager'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer')], default='CONTRIBUTOR', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_member',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='home.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('EXPIRED_RESOLVED', 'Expired (resolved)')], default='UNCLAIMED', max_length=30)),
                ('allow_multiclaim', models.BooleanField(default=False)),
                ('is_residual', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.gate')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residual_tasks', to='home.task')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='HandoverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_done', models.TextField()),
                ('work_remaining', models.TextField()),
                ('blocker_reason', models.TextField()),
                ('percent_completed', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handover_reports', to=settings.AUTH_USER_MODEL)),
                ('spawned_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_from_report', to='home.task')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_report', to='home.task')),
            ],
            options={
                'db_table': 'handover_report',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Lead', 'Lead'), ('Contributor', 'Contributor')], default='Contributor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_profiles', to='home.task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('auto_claim_reminder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user settings',
                'db_table': 'user_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='gate',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_order'), name='uq_gate_project_sequence_order'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uq_project_member_project_user'),
        ),
        migrations.AddConstraint(
            model_name='handoverreport',
            constraint=models.CheckConstraint(condition=models.Q(('percent_completed__gte', 0), ('percent_completed__lt', 100)), name='ck_handover_percent_completed_0_99'),
        ),
    ]
